controllers/SelectController.php
<?php

namespace app\controllers;


use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

class SelectController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    '*' => ['post'],
                ],
            ],
        ];
    }

    public function actionSelectRequestedCount()
    {

        return ['data' => Services::getRequestedCount()];
    }

    public function beforeAction($action)
    {

        Yii::$app->response->format = Response::FORMAT_JSON;
        return parent::beforeAction($action);
    }

}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\RememberForm;
use app\models\Users;
use app\models\UsersSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'delete', 'create', 'update', 'remember-pass'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Users::validateRol(Users::ROL_ADMIN);
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        //$dataProvider->query->andWhere(['rol' => Users::ROL_USER]);

        $dataProvider->sort->defaultOrder = ['enabled' => SORT_DESC, 'id' => SORT_DESC];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post())) {

            $model->admin = Yii::$app->request->post('Users')['admin'];

            //dd($model->admin);
            $model->rol = ($model->admin) ? Users::ROL_ADMIN : Users::ROL_USER;

            if ($model->save()) {
                $modelPass = new RememberForm();
                $modelPass->email = $model->email;


                if ($modelPass->sendEmailNew()) {
                    Yii::$app->session->setFlash('success', 'Usuario creado correctamente');
                } else {
                    Yii::$app->session->setFlash('danger', 'No pudimos enviar el mail, intenta de nuevo');
                    $model->delete();
                    return $this->render('create', [
                        'model' => $model,
                    ]);
                }

                //Resetear token
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                // dd($model->getErrors());
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        } else {

            $model->enabled = STATUS_ACTIVO;
            //$model->genero_id=Genero::GENERO_M;
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->admin = Yii::$app->request->post('Users')['admin'];

            //dd($model->admin);
            $model->rol = ($model->admin) ? Users::ROL_ADMIN : Users::ROL_USER;

            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Usuario actualizado correctamente');
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                $model->password = "";
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $model->admin = $model->rol == Users::ROL_ADMIN;
            $model->password = "";
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->identity->id == $id || Users::validateRol(Users::ROL_ADMIN, $id)) {

            Yii::$app->session->setFlash('danger', 'No se puede eliminar un usuario Admin');
            return $this->redirect(['index']);
        }

        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('success', 'Usuario eliminado correctamente');
        return $this->redirect(['index']);
    }


    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {

        if (($model = Users::findOne($id)) !== null) {

            if (Users::validateRol(Users::ROL_ADMIN)) {
                return $model;
            } else {
                throw new ForbiddenHttpException('No tienes permiso para acceder a este elemento');
            }
        } else {
            throw new NotFoundHttpException('Usuario no existe');
        }
    }
}

views/layouts/content.php
<?php

use yii\widgets\Breadcrumbs;
?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                }
                ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        )
        ?>
    </section>

    <section class="content">
        <?php showFLash(); ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; <?= hoy('Y') ?> <a href="#"><?= Yii::$app->params['appName'] ?></a></strong> All rights reserved - Developed by <a href="http://www.kompile.co" target="_blank">Kompile</a>
</footer>


<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/layouts/header.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use richardfan\widget\JSRegister;
/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini"><span class="md">' . Html::img('@web/img/icon.png', ['height' => '35']) . '</span></span>
	<span class="logo-lg">' . Html::img('@web/img/logo2.png', ['height' => '35']) . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">




                <!-- User Account: style can be found in dropdown.less -->
                <?php if (!Yii::$app->user->isGuest) : ?>

                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span id='label-count' class="label label-warning"><?= '2' ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">Last 5 requested services</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <li>

                                        <a target=_blank href="#">
                                            <i class="fa fa-asterisk text-aqua"></i> <?= 'abc - 123' ?>
                                        </a>

                                        <a href="#">
                                            <i class="fa fa-ban"></i> There's no services in "requested" status
                                        </a>


                                    </li>
                                </ul>
                            </li>
                            <li class="footer"><a href="<?= Url::to(['services/index']) ?>">Ver todos</a></li>
                        </ul>
                    </li>

                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user"></i>
                            <span class="hidden-xs"><?= Yii::$app->user->identity->name ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <?= Html::img('@web/img/icon.png', ['height' => '35', 'class' => 'img-circle']) ?>


                                <p>
                                    <?= Yii::$app->user->identity->name ?>
                                    <small><?= Yii::$app->user->identity->email ?></small>
                                </p>
                            </li>
                            <!-- Menu Body 
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <!--<a href="#" class="btn btn-default btn-flat">Profile</a>-->
                                </div>
                                <div class="pull-right">
                                    <?=
                                    Html::a(
                                        'Cerrar sesión',
                                        [Url::to('site/logout')],
                                        ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                    )
                                    ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                <?php endif; ?>

                <!-- User Account: style can be found in dropdown.less -->

            </ul>
        </div>
    </nav>
</header>
<?php JSRegister::begin(['position' => static::POS_END]); ?>
<script>
    window.setInterval(function() {

        $.post("<?= Url::to(['select/select-requested-count']) ?>", function(data) {
            if (data.hasOwnProperty('data')) {
                $("#label-count").text(data.data);

            }
        });


    }, 60 * 1000);
</script>
<?php JSRegister::end(); ?>

views/layouts/left.php
<?php

use yii\helpers\Url;
use app\models\Users;
?>
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel 
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form  -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Buscar..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        <?php
        //  dd(Url::current());

        if (Users::validateRol(Users::ROL_ADMIN)) {
            $menu = [
                ['label' => 'Dashboard', 'options' => ['class' => 'header']],
                ['label' => 'Home', 'icon' => 'dashboard', 'url' => [Url::to('/')], 'active' => (Url::current() == Url::home() . 'index') ? true : false],
                ['label' => 'Title', 'options' => ['class' => 'header']],
                [
                    'label' => 'Menu1',
                    'icon' => 'asterisk',
                    'url' => '#',
                    'items' => [
                        ['label' => 'Create', 'icon' => 'plus', 'url' => [Url::to('/services/create')],],
                        ['label' => 'List', 'icon' => 'list', 'url' => [Url::to('/services/index')], 'active' => strpos(Url::current(), 'services') && !strpos(Url::current(), 'create') ? true : false],
                    ],
                ],
                //  ['label' => 'Users management', 'options' => ['class' => 'header']],
                [
                    'label' => 'Usuarios',
                    'icon' => 'users',
                    'url' => '#',
                    'items' => [
                        ['label' => 'Crear', 'icon' => 'plus', 'url' => [Url::to('/users/create')],],
                        ['label' => 'Listado', 'icon' => 'list', 'url' => [Url::to('/users/index')], 'active' => strpos(Url::current(), 'users') && !strpos(Url::current(), 'create') ? true : false],
                    ],
                ],
           
                ['label' => 'System parameters', 'options' => ['class' => 'header']],
                [
                    'label' => 'Cities',
                    'icon' => 'globe',
                    'url' => [Url::to('/cities/index')],
                    'active' => strpos(Url::current(), 'cities')
                ],
            ];
        }



        echo (!Yii::$app->user->isGuest) ? dmstr\widgets\Menu::widget([
                    'options' => ['class' => 'sidebar-menu'],
                    'items' => $menu
                ]) : ''
        ?>

    </section>

</aside>

views/layouts/main-login.php
<?php

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use richardfan\widget\JSRegister;

/* @var $this \yii\web\View */
/* @var $content string */
app\assets\AppAsset::register($this);
$directoryAsset = Url::to('@web');
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => Url::to(['/img/favicon.png'])]);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode(Yii::$app->params['shortName'].' | ' . $this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="login-page">

        <?php $this->beginBody() ?>
        <div class="col-md-6 col-md-offset-3 flash-main">
            <?php showFLash(); ?>
        </div>
        <?= $content ?>

        <?php JSRegister::begin(['position' => static::POS_END]); ?>

        <script>
            /*(function () {
                var options = {
                whatsapp: "+573143732575", // WhatsApp number
                    call_to_action: "Do you need technical support?", // Call to action
                    position: "right", // Position may be 'right' or 'left'
                };
                var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
                var s = document.createElement('script');
                s.type = 'text/javascript';
                s.async = true;
                s.src = url + '/widget-send-button/js/init.js';
                s.onload = function () {
                    WhWidgetSendButton.init(host, proto, options);
                };
                var x = document.getElementsByTagName('script')[0];
                x.parentNode.insertBefore(s, x);
            })();*/

        </script>

        <?php JSRegister::end(); ?>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use richardfan\widget\JSRegister;
use cybercog\yii\googleanalytics\widgets\GATracking;

/* @var $this \yii\web\View */
/* @var $content string */
app\assets\AppAsset::register($this);

$directoryAsset = Url::to('@web');
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => Url::to(['/img/favicon.png'])]);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode(Yii::$app->params['shortName'].' | ' . $this->title) ?></title> 
        <?php $this->head() ?>

    </head>
    <body class="hold-transition fixed skin-yellow sidebar-mini ">
        <?php $this->beginBody() ?>
        <div class="wrapper">

            <?=
            $this->render(
                    'header.php', ['directoryAsset' => $directoryAsset]
            )
            ?>

            <?=
            $this->render(
                    'left.php', ['directoryAsset' => $directoryAsset]
            )
            ?>

            <?=
            $this->render(
                    'content.php', ['content' => $content, 'directoryAsset' => $directoryAsset]
            )
            ?>

        </div>

        <?php JSRegister::begin(['position' => static::POS_BEGIN]); ?>
        <script>

            (function () {
                if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
                    var body = document.getElementsByTagName('body')[0];
                    body.className = body.className + ' sidebar-collapse';
                }
            })();
        </script>

        <?php JSRegister::end(); ?>


        <?php JSRegister::begin(['position' => static::POS_END]); ?>
        <script>
          /* (function () {
                var options = {
                    whatsapp: "+573143732575", // WhatsApp number
                    call_to_action: "¿Necesitas soporte técnico?", // Call to action
                    position: "right", // Position may be 'right' or 'left'
                };
                var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
                var s = document.createElement('script');
                s.type = 'text/javascript';
                s.async = true;
                s.src = url + '/widget-send-button/js/init.js';
                s.onload = function () {
                    WhWidgetSendButton.init(host, proto, options);
                };
                var x = document.getElementsByTagName('script')[0];
                x.parentNode.insertBefore(s, x);
            })();*/

        </script>

        <?php JSRegister::end(); ?>

        <?php JSRegister::begin(['position' => static::POS_END]); ?>
        <script>

            // Click handler can be added latter, after jQuery is loaded...
            $('.sidebar-toggle').click(function (event) {
                event.preventDefault();
                if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
                    sessionStorage.setItem('sidebar-toggle-collapsed', '');
                } else {
                    sessionStorage.setItem('sidebar-toggle-collapsed', '1');
                }
            });
        </script>

        <?php JSRegister::end(); ?>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>